title: My Test Blog
author: GitHub User
description: > # this means to ignore newlines until "baseurl:"
  trying to see if this will work for blogging... 🤞

show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag